CC = gcc
CFLAGS = -Wall -g

all: syscall_tracer test_program

syscall_tracer: syscall_tracer.c
    $(CC) $(CFLAGS) -o syscall_tracer syscall_tracer.c

test_program: test_program.c
    $(CC) $(CFLAGS) -o test_program test_program.c

clean:
    rm -f syscall_tracer test_program test.txt
